/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package tools.functionaljava.validationcore;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
